<!DOCTYPE html>  
<html lang="en">  
    <head>
        <meta charset="UTF-8">
        <title>Goldeneye</title>
    </head>
    <body>
        <h1>Goldeneye</h1>
        <h2>Obtener email</h2>
        <form action="/" method="post">
            <label for="Name">Nombre:</label><br>
            <input type="text" id="Name" name="Name"><br>
            <label for="Surname">Apellido:</label><br>
            <input type="text" id="Surname" name="Surname"><br>
            <label for="Office">Oficina:</label><br>
            <input type="text" id="Office" name="Office"><br>
            <label for="Department">Departamento:</label><br>
            <input type="text" id="Department" name="Department"><br><br>
            <input type="submit" value="Enviar">
        </form>


    </body>
</html>